
title: Jose Paredes
url: "https://jparedesDS.github.io/"
baseurl: ""
#remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "#"
footer_text: "Click here if you'd like to collaborate with me:)"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Curriculum Vitae"
   link: "resume.pdf"
# - name: "Google Scholar"
#  link: "https://scholar.google.com.au/citations?user=-hYjPxsAAAAJ&hl=en&oi=ao"
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/krishanrana/"
 - name: "GitHub"
   link: "https://github.com/jparedesDS"
 - name: "Twitter"
   link: "https://twitter.com/xhitoCS"
 
 

# author:
#   name:       Krishan Rana
#   url:        https://krishanrana.github.io/
