
title: Jose Paredes
url: "https://jparedesDS.github.io/"
baseurl: ""
#remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "#"
footer_text: "Click here if you'd like to collaborate with me:)"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "CV"
   link: "resume.pdf"
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/jparedesDS/"
 - name: "GitHub"
   link: "https://github.com/jparedesDS"
 - name: "Kaggle"
   link: "https://www.kaggle.com/joseparedesc"
 - name: "Twitter"
   link: "https://twitter.com/xhitoCS"
 
 

# author:
#   name:       Krishan Rana
#   url:        https://krishanrana.github.io/

