
title: Krishan Rana
url: "https://krishanrana.github.io/"
baseurl: ""
#remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://docs.google.com/forms/d/e/1FAIpQLSeKV1Ln1Y7mFm9Wuy4nELk_aTAMpRDLDhiu2EKV0wU_fptFQA/viewform?usp=sf_link"
footer_text: "Click here if you'd like to collaborate :)"

sass:
    style: compressed
    sass_dir: _sass

nav:
 # - name: "Resume"
 #   link: "resume.pdf"
 - name: "Google Scholar"
   link: "https://scholar.google.com.au/citations?user=-hYjPxsAAAAJ&hl=en&oi=ao"
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/krishanrana/"
 - name: "Twitter"
   link: "https://twitter.com/krshnrana"
 
 

# author:
#   name:       Krishan Rana
#   url:        https://krishanrana.github.io/

